# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=separator

--separator
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--separator--

###

# @name create-transcription
POST http://localhost:3333/videos/8cdf8469-ce60-4267-92c4-72ebb7cf92dd/transcription
Content-Type: application/json

{
  "prompt": "youtube, ai"
}


###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "8cdf8469-ce60-4267-92c4-72ebb7cf92dd",
  "template": "Generate short resume of transcription of video about this video: '''{transcription}'''",
  "temperature": 0.5
}